[package]
name = "stattest"
version = "0.0.1"
authors = ["Lars Willighagen <lars.willighagen@gmail.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
statrs = { git = "https://github.com/larsgw/statrs", branch = "patch-1" }
rand = "0.7.3"
